postgresql:
  restart: always
  image: postgres:9.6.2-alpine
  environment:
    - POSTGRES_USER=gitlab
    - POSTGRES_PASSWORD=gitlab
    - POSTGRES_DB=gitlabhq_production
# the following are hints on what volumes to mount if you want to persist data
  volumes:
    - /op/postgresql/data/postgresql:/var/lib/postgresql:rw